name: Deploy to Server via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SSH to Server
        with:
          host: 142.93.150.193
          username: stageccat
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/1018477.cloudwaysapps.com/wvgxnmfydt/public_html/auto
            git pull origin main
