name: Deploy to Cloudways on Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Cloudways
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.CLOUDWAYS_KEY }}
        script: |
          cd /home/1018477.cloudwaysapps.com/wvgxnmfydt/public_html/auto
          git pull origin main
          
 
