name: Deploy to Cloudways

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.CLOUDWAYS_SSH_KEY }}

      - name: Deploy to Cloudways
        run: |
          ssh -i ~/.ssh/cloudways.key stageccat@142.93.150.193 "cd /home/1018477.cloudwaysapps.com/wvgxnmfydt/public_html/auto && git pull origin main"
